### ISSUE TITLE
Update-MgUserAuthenticationPhoneMethod of module Microsoft.Graph.Identity.SignIns

### ISSUE THREAD

**Issue by Juurox** [adamedx/autographps-sdk#63]
**Describe the bug**
Script Update-MgUserAuthenticationPhoneMethod is not working due to wrong http method.

**Logs -- please attach the following data for failures executing a command
![image](https://user-images.githubusercontent.com/93762414/140479685-3a243f9a-ab8b-4f55-9712-3b3f5312dbbd.png)

**Additional context**
Changing http method from PATCH to PUT will be able to fix the bug.
![image](https://user-images.githubusercontent.com/93762414/140479061-83d069a7-9bfb-4acd-835c-df2c8cbb0fd1.png)
![image](https://user-images.githubusercontent.com/93762414/140479314-941c8e16-0bbd-4982-9937-251c1d5f4459.png)

**Comment by adamedx** [comment]
Hello -- I think you posted this issue to the wrong repository. From the command name and module names I think you are looking for this repo: https://github.com/microsoftgraph/msgraph-sdk-powershell/issues.

Let me know if you think otherwise...
